# Generated by Django 5.2.8 on 2026-01-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
