# Generated by Django 5.2.8 on 2026-01-17 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychat', '0003_alter_shop_lat_alter_shop_lng'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='room',
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mychat.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
